### PR TITLE
Updating caution icon

### PR DESCRIPTION
**Pull request by bergerhoffer**
Fixing caution icon from #250 

Original issue #249 

Preview: http://file.rdu.redhat.com/~ahoffer/2022/main-bios.html#bios

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@sbmetz @bburt-rh @ndeevy @bredamc Can you review? Also fixed the italics -> quotes for the new sweep we're doing.

**Review by bburt-rh — APPROVED** [review]

**Review by ndeevy — APPROVED** [review]
LGTM!

**Comment by bburt-rh** [comment]
3 approvals, so I'm merging this.

**Pull request merged**
