### PR TITLE
adds terms to the glossary

### PR DESCRIPTION
**Pull request by Amrita42**
The scope of this PR is to propose terms that are specific to OCP.

Replaces #222

### CODE REVIEW

**Comment by bburt-rh** [comment]
LGTM. Approved.

**Review by bburt-rh — APPROVED** [review]

**Review by bergerhoffer — APPROVED** [review]
LGTM!

**Review by ndeevy — APPROVED** [review]

**Comment by ndeevy** [comment]
LGTM @Amrita42  Thanks for generalizing those two terms :-]

**Comment by Amrita42** [comment]
Thank you @bergerhoffer @bburt-rh and @ndeevy for your review feedback/approvals.

**Pull request merged**
