### PR TITLE
Add Vale checks to the SSG

### PR DESCRIPTION
**Pull request by aireilly**
This PR builds on the sterling work done by @bburt-rh in https://github.com/redhat-documentation/supplementary-style-guide/pull/336 to hopefully allow us to merge this update to the SSG that lints AsciiDoc source for errors.

This PR adds:

* [A vale action that highlights errors in PRs](https://github.com/redhat-documentation/supplementary-style-guide/pull/402/commits/d9116463deacdc8a51a7857eb6e4fe1f2cf541d6)
* Vale config files
* Vale Vocab files. Vocabs are a project convenience to quickly remove terms from being highlighted by Vale. 
* `[.vale-ignore]` AsciiDoc classes to all the *Incorrect forms* terms. This removes them from Vale errors, reducing the noise in the error logs significantly. 

With the above changes, the errors look like this: http://pastebin.test.redhat.com/1109996 

To review the work and see how it feels in the editor, [install Vale](https://redhat-documentation.github.io/vale-at-red-hat/docs/main/user-guide/installing-vale-cli/), check out this PR, and run `vale sync` from the SSG source folder.

The following errors are disabled to reduce noise in the output:

* [RedHat.CaseSensitiveTerms](https://github.com/redhat-documentation/vale-at-red-hat/blob/main/.vale/styles/RedHat/CaseSensitiveTerms.yml)
* [RedHat.ConsciousLanguage](https://github.com/redhat-documentation/vale-at-red-hat/blob/main/.vale/styles/RedHat/ConsciousLanguage.yml)
* [RedHat.Definitions](https://github.com/redhat-documentation/vale-at-red-hat/blob/main/.vale/styles/RedHat/Definitions.yml)
* [RedHat.DoNotUseTerms](https://github.com/redhat-documentation/vale-at-red-hat/blob/main/.vale/styles/RedHat/DoNotUseTerms.yml)
* [RedHat.Headings](https://github.com/redhat-documentation/vale-at-red-hat/blob/main/.vale/styles/RedHat/Headings.yml)
* [RedHat.PascalCamelCase](https://github.com/redhat-documentation/vale-at-red-hat/blob/main/.vale/styles/RedHat/PascalCamelCase.yml)
* [RedHat.SimpleWords](https://github.com/redhat-documentation/vale-at-red-hat/blob/main/.vale/styles/RedHat/SimpleWords.yml)

### CODE REVIEW

**Comment by aireilly** [comment]
pastebin of current errors:
https://privatebin.corp.redhat.com/?88b2674b3eb93b40#GFUX3K5ScMvDsrMHR3jyfC3tycyZDnDgfSQNnPELEoNd

**Comment by dfitzmau** [comment]
Hi @aireilly . I followed your instructions and I was able to run Vale from my locally cloned SSG repo. Thanks! Great work. 

From the output, I see some "RedHat.SimpleWords" errors generated but from the list in this PR, this error type should be disabled?

Screenshot from 2023-10-03 13-57-00

**Comment by dfitzmau** [comment]
> > CaseSensitiveTerms
> 
> They are already turned off: `RedHat.CaseSensitiveTerms = NO` and `RedHat.SimpleWords = NO`. Change to the SSG folder and run again please.
> 
> ```
> ┌───── ~/supplementary-style-guide (brian-vale-pr)
> $ vale sync && vale .
> ```

Thanks. I checked out the branch with `gh pr checkout 402` and then ran `vale sync && .vale`. The output looks good. My result count:

Screenshot from 2023-10-03 14-16-44

**Comment by aireilly** [comment]
> > > CaseSensitiveTerms
> > 
> > 
> > They are already turned off: `RedHat.CaseSensitiveTerms = NO` and `RedHat.SimpleWords = NO`. Change to the SSG folder and run again please.
> > ```
> > ┌───── ~/supplementary-style-guide (brian-vale-pr)
> > $ vale sync && vale .
> > ```
> 
> Thanks. I checked out the branch with `gh pr checkout 402` and then ran `vale sync && .vale`. The output looks good. My result count:
> 
> Screenshot from 2023-10-03 14-16-44

Perfect. Now for the _qualitative_ side. How does this _feel_ when applied to the SSG source files. Do the errors make sense? Are the suggestions useful? Are there false positives? incorrectly flagged terms? This is what we need to review - This Vale addition should help SSG updates, not hinder them.

**Comment by dfitzmau** [comment]
> > > > CaseSensitiveTerms
> > > 
> > > 
> > > They are already turned off: `RedHat.CaseSensitiveTerms = NO` and `RedHat.SimpleWords = NO`. Change to the SSG folder and run again please.
> > > ```
> > > ┌───── ~/supplementary-style-guide (brian-vale-pr)
> > > $ vale sync && vale .
> > > ```
> > 
> > 
> > Thanks. I checked out the branch with `gh pr checkout 402` and then ran `vale sync && .vale`. The output looks good. My result count:
> > Screenshot from 2023-10-03 14-16-44
> 
> Perfect. Now for the _qualitative_ side. How does this _feel_ when applied to the SSG source files. Do the errors make sense? Are the suggestions useful? Are there false positives? Incorrectly flagged terms? This is what we need to review - This Vale addition should help SSG updates, not hinder them.

On running Vale against the `f.adoc` file, the output looks good and makes sense. Detecting false positive might take a bit more time as running vale against each file might be necessary; from here, each error line item would need to be checked. 

Screenshot from 2023-10-03 14-16-44

**Comment by aireilly** [comment]
I'll update to remove erroneous spelling errors.

**Comment by bredamc** [comment]
@aireilly Can you please resolve the file conflicts? Do you plan to make any other changes to this PR, or is it ready for review and approval?

**Comment by aireilly** [comment]
@bredamc This is updated and ready for final review/merge. To review, check out the PR, run `vale sync` from the root of the repo, and then run `vale . --minAlertLevel=error` to review the errors. The Vale config has been "tuned" with a list of words that are skipped from the Vale spelling check in the Vocab folder.

**Review by dfitzmau — APPROVED** [review]
LGTM 

Screenshot from 2023-11-07 09-55-47

**Comment by aireilly** [comment]
Any update on this one? I think it just needs one more lgtm to be merged.

**Review by dfitzmau — APPROVED** [review]

**Pull request merged**
