### PR TITLE
updated Patternfly links

### PR DESCRIPTION
**Pull request by mportman12**
The current Patternfly links in the SSG are out of date and hit 404 errors. This PR updates the links to the correct URLs.

### CODE REVIEW

**Review by bburt-rh — APPROVED** [review]
LGTM

**Review by bergerhoffer — APPROVED** [review]
LGTM!

**Review by ndeevy — APPROVED** [review]
Looks good.

**Comment by bburt-rh** [comment]
3 approvals. Merging.

**Pull request merged**
