### PR TITLE
Corrected typos to improve clarity

### PR DESCRIPTION
**Pull request by heymichellemac**
Found some typos while reading through the documentation for m.adoc so went ahead and corrected them for clarity.

### CODE REVIEW

**Review by mportman12 — APPROVED** [review]
LGTM! Thanks for fixing these!

**Review by bburt-rh — APPROVED** [review]

**Comment by bburt-rh** [comment]
Lgtm, too. Thanks for the fixes!

**Comment by heymichellemac** [comment]
Excellent thanks for the quick review :D

**Review by bergerhoffer — APPROVED** [review]
LGTM, thanks for submitting this!

**Pull request merged**
