### PR TITLE
Renaming master.adoc to main.adoc

### PR DESCRIPTION
**Pull request by bergerhoffer**
With the effort of #212, renaming master.adoc to main.adoc.

The renaming of the 'master' branch to 'main' will come later.

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@bburt-rh @redhat-documentation/ccs-style-council Can I get a few reviews/approvals please? This is the first step in the master->main switch. I will make the branch change sometime after this PR is merged.

**Review by bburt-rh — APPROVED** [review]

**Comment by bburt-rh** [comment]
looks good to me. Thanks @bergerhoffer

**Review by ncbaratta — APPROVED** [review]
lgtm

**Comment by Amrita42** [comment]
lgtm

**Review by Amrita42 — APPROVED** [review]

**Comment by bergerhoffer** [comment]
3 project approvals, merging!

**Pull request merged**
