### PR TITLE
Adding icons for whether to use terms

### PR DESCRIPTION
**Pull request by bergerhoffer**
Addresses #58.

Started with updates just to A and B terms, to make sure we like it before I make the updates to all terms.

Preview (internal): http://file.rdu.redhat.com/~ahoffer/2021/ssg_icons/master.html#_a

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@redhat-documentation/ccs-style-council Please take a look at the preview link (letters A and B) and let me know if you like it or have any feedback!

**Comment by ndeevy** [comment]
They look ace! 
Only comment is that maybe they're a little subtle but I think that's just because of the general style the guide has. Iirc, there was discussion about changing the general style, was there any movement on that idea?
(it it's not broken though ¯\_(ツ)_/¯ )

**Comment by bergerhoffer** [comment]
> They look ace!
> Only comment is that maybe they're a little subtle but I think that's just because of the general style the guide has. Iirc, there was discussion about changing the general style, was there any movement on that idea?
> (it it's not broken though ¯_(ツ)_/¯ )

@ndeevy Thanks, yeah I might've liked them to be just a little bit bolder, but these icons were taken from our brand-approved icon repo (and colored by Jess Schaefer for us). I think they'll do the job, but if others feel like we need them to be bolder, we can always see if that's a possibility.

As for changing the style of the guide, I'm not aware of any movement on that (or even know how it would be done). It might be possible to change, but I believe the mod docs guide and AsciiDoc markup guide both use the same styling. So if we really want to change it, we should probably check with the mod docs group first to see if they'd be willing to do the same, to keep things consistent across the guides.

**Comment by ndeevy** [comment]
@bergerhoffer thank you, ok understood. Consistency is king! and they look good and are a great addition. Just thought I remembered a conversation in a style council meeting about someone wanting to look into changing the style sheets but never mind, probably misremembering :-]

**Review by leswilliams44 — APPROVED** [review]
LGTM

**Comment by inoxx03** [comment]
You remember correctly, @ndeevy Changing the general style is on me. to be honest I haven't really done much about it to date, but I haven't forgotten about it. I'll look for some alternative icon designs, maybe we could go with a style similar to this: 
73497077-tick-and-cross-signs-green-checkmark-ok-and-red-x-icons-isolated-on-white-background-simple-marks-gr

That being said, the current design still looks great:)

**Review by inoxx03 — APPROVED** [review]

**Review by ndeevy — APPROVED** [review]

**Comment by ndeevy** [comment]
> You remember correctly, @ndeevy. Changing the general styling is on me (I signed up to do it):) To be honest I haven't really done much about it to date, but I definitely haven't forgotten about it:) I'll look for some alternative icon designs, maybe we could go with a style similar to this:

Ahh ok @inoxx03, thanks! It's a big topic anyhow and there are more than enough PRs to keep us busy at the moment! :-D 
These ones look good though.

> 73497077-tick-and-cross-signs-green-checkmark-ok-and-red-x-icons-isolated-on-white-background-simple-marks-gr
> 
> That being said, the current design still looks great:)
Agreed ;-)  I guess they fit with the general styling of the guide, no harm if they're a bit gentle on the eye :-D

**Comment by bergerhoffer** [comment]
Even though this PR is only adding icons for A and B, I'm going to merge it so that the icons are available for others to add them to the rest of the letters. We'll try to get these wrapped up in a few days

**Pull request merged**
