### PR TITLE
Added info about single step procedures

### PR DESCRIPTION
**Pull request by mportman12**
Added guidance about using an unnumbered bullet for single step procedures.

### CODE REVIEW

**Review by bergerhoffer — APPROVED** [review]
LGTM!

**Review by ndeevy — APPROVED** [review]

**Review by leswilliams44 — COMMENTED** [review]
Should "Single step procedures" be "Single-step procedures" if single step is a compound modifier?

**Comment by mportman12** [comment]
> Should "Single step procedures" be "Single-step procedures" if single step is a compound modifier?

@leswilliams44 Added hyphen

**Comment by bergerhoffer** [comment]
Merging (enough approvals when including those from prior to the last tweak).

**Pull request merged**
