### PR TITLE
Adding link to stylepedia style guide

### PR DESCRIPTION
**Pull request by bergerhoffer**
Per #236, linking to the stylepedia style guide, in case folks outside of CCS land on our SSG.

Preview: http://file.rdu.redhat.com/~ahoffer/2022/main-stylepedia.html#_about_this_guide

@daobrien to add a similar link in the stylepedia landing page and guides to link to the SSG for CCS folks.

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@redhat-documentation/ccs-style-council @daobrien for review please!

Preview: http://file.rdu.redhat.com/~ahoffer/2022/main-stylepedia.html#_about_this_guide

**Comment by bburt-rh** [comment]
This lgtm, but with one question: the ISG says to use headline capitalization for "Titles of stand-alone information units, such as quick start guides or discrete sets of product documentation." So shouldn't it be "Red Hat Supplementary Style Guide" in the Note?

**Comment by bergerhoffer** [comment]
> This lgtm, but with one question: the ISG says to use headline capitalization for "Titles of stand-alone information units, such as quick start guides or discrete sets of product documentation." So shouldn't it be "Red Hat Supplementary Style Guide" in the Note?

@bburt-rh The official title of our guide is "Red Hat supplementary style guide for product documentation" sentence case, so that's why it's like that here. (Unless I'm missing your point). In CCS, we use sentence case throughout, I believe even in guide titles.

**Comment by bburt-rh** [comment]
> > This lgtm, but with one question: the ISG says to use headline capitalization for "Titles of stand-alone information units, such as quick start guides or discrete sets of product documentation." So shouldn't it be "Red Hat Supplementary Style Guide" in the Note?
> 
> @bburt-rh The official title of our guide is "Red Hat supplementary style guide for product documentation" sentence case, so that's why it's like that here. (Unless I'm missing your point). In CCS, we use sentence case throughout, I believe even in guide titles.

@bergerhoffer Ok. It just looks funny to my eyes to see a title of a whole document in italics and sentence case. Also, if we do deviate from the ISG guidance regarding headline case for titles of "stand-alone information units", then maybe we should consider encoding that in the SSG, since I can't seem to find any info about this exception. Or am I misunderstanding what type of document this is?

**Comment by bergerhoffer** [comment]
> > > This lgtm, but with one question: the ISG says to use headline capitalization for "Titles of stand-alone information units, such as quick start guides or discrete sets of product documentation." So shouldn't it be "Red Hat Supplementary Style Guide" in the Note?
> > 
> > 
> > @bburt-rh The official title of our guide is "Red Hat supplementary style guide for product documentation" sentence case, so that's why it's like that here. (Unless I'm missing your point). In CCS, we use sentence case throughout, I believe even in guide titles.
> 
> @bergerhoffer Ok. It just looks funny to my eyes to see a title of a whole document in italics and sentence case. Also, if we do deviate from the ISG guidance to use headline case for titles of "stand-alone information units", then maybe we should consider encoding that in the SSG, since I can't seem to find any info about this exception. Or am I misunderstanding what type of document this is?

Actually you make a fair point that I didn't italicize the guide names, which we do elsewhere in the guide. So I will update to do that.

As for an exception on the case, I'm not sure. When we moved to sentence case a few years ago, I was always under the assumption that that meant guide titles too. I guess I'm not sure why the guide title would follow any different casing. We do sentence case for guide titles on OpenShift, and a spot check of other doc sets vary.

For this PR, the sentence case is correct, since that's how the guide is titled. But if we do decide we that need to change it, we can make that change throughout the whole guide in a separate PR.

@IngridT1 I think you were involved a lot in the shift to sentence case in CCS a few years ago. Do you know what our stance on it for guide titles was/is?

**Comment by bburt-rh** [comment]
> I guess I'm not sure why the guide title would follow any different casing

@bergerhoffer @IngridT1 The ISG provides the following guidance, and I can't seem to find anyplace where we say that we are deviating from this guidance, but maybe I'm missing something:

```
Use headline-style capitalization for these items:

- Titles of books
- Titles of CDs
- Titles of stand-alone information units, such as quick start guides or discrete sets of product documentation
- Titles of events, such as training courses or programs
- Titles of videos

```

**Comment by bredamc** [comment]
@bergerhoffer Am I correct in thinking that this PR is ready for review? If it is deemed necessary to change the title from sentence-case to headline-case, that change will be covered in a different PR?

**Comment by bergerhoffer** [comment]
@bredamc Yes it's ready for review, thanks! And yeah if we need to make case changes, that will be done in a separate PR. I'd like to hear @IngridT1's thoughts/memory on that subject before we make any decisions on that.

**Review by ncbaratta — APPROVED** [review]
The changes to the guide look a-ok to me.  The stylepedia HTML file won't load up though so I'm not sure if that needs review and approval.

**Comment by daobrien** [comment]
This is on my list to do but I'm flooded with editing work atm. I'll get to it asap.

**Comment by daobrien** [comment]
> The changes to the guide look a-ok to me. The stylepedia HTML file won't load up though so I'm not sure if that needs review and approval.

WFM. Which URL did it take you too, and what error messages did you see?
Bear in mind too that we're about to release 6.0 of this guide so the landing page will change a bit. That won't affect the URL, though.

**Comment by bburt-rh** [comment]
lgtm

**Comment by ncbaratta** [comment]
> @ncbaratta Are you talking about stylepedia.net site, or my preview file above (http://file.rdu.redhat.com/~ahoffer/2022/main-stylepedia.html#_about_this_guide)? If it's the preview file, you'd have to be on VPN to view it.

I mean the file that shows as the second file here: https://github.com/redhat-documentation/supplementary-style-guide/pull/251/files
Screen Shot 2022-11-15 at 10 45 21 AM

**Review by sbmetz — APPROVED** [review]

**Comment by bburt-rh** [comment]
3 approvals in, so merging now.

**Comment by bergerhoffer** [comment]
Shoot @ncbaratta I see it now, I hadn't noticed that. That was an accidental inclusion of a preview build file. I'll submit a PR to remove it and will update the gitignore file so I don't do that again! :slightly_smiling_face:

**Comment by bergerhoffer** [comment]
Whoever has a moment to review, I have two PRs to fix this:
* #257 to remove the accidentally included file
* #258 to update .gitignore so it doesn't happen again!

**Comment by ncbaratta** [comment]
Oh good! It wasn't supposed to be there :)

**Comment by bredamc** [comment]
Well spotted, @ncbaratta :clap:

**Pull request merged**
