### PR TITLE
Adding guidelines for style entries

### PR DESCRIPTION
**Pull request by bergerhoffer**
@redhat-documentation/ccs-style-council Style entry guidance, please review! Let me know if you can think of any considerations that we need to add here.

See https://github.com/redhat-documentation/supplementary-style-guide/blob/master/supplementary_style_guide/style_guidelines/graphical-interfaces.adoc for an example implementation.

### CODE REVIEW

**Comment by roldanbob** [comment]
Curious about the decision behind the text entry guidance. The IBM Style Guide says to use "type" to indicate that a user should provide text. I suspect that is the usage that is most common across our docs, but I haven't really investigated that hypothesis.

I was also going to say something about using `->` vs just `>` to concatenate a sequence of menu commands, but then I tested it out and saw that asciidoc converts the first one into an arrow. Cool! I never knew that.

**Comment by sterobin** [comment]
@roldanbob Apparently both "enter" and "type" are permitted. See "type" under Word Usage: https://www.ibm.com/developerworks/library/styleguidelines/  I think the team decided on "enter" just because having the two options was creating inconsistency even with the same documents, and might have misled. I think the idea was to just choose one for simplicity, and "enter" was voted as most favorable by the majority. That's all, I believe.

**Comment by stoobie** [comment]
> @roldanbob Apparently both "enter" and "type" are permitted, and even "issue" in the case of CLI. See "type" under Word Usage: https://www.ibm.com/developerworks/library/styleguidelines/ I think the team decided on "enter" just because having the two options was creating inconsistency even with the same documents, and might have misled. I think the idea was to just choose one for simplicity, and "enter" was voted as most favorable by the majority. That's all, I believe.
@roldanbob @sterobin **Enter** includes inputting the text and hitting the "Enter/Return" key, or whatever button might do the same thing. **Type** literally means "Hit the keys on your keyboard". It doesn't necessarily mean that you should hit the "Enter" key.

**Comment by sterobin** [comment]
@stoobie Absolutely, makes sense. I think that's the simplification this change is intentionally making, i.e., not worry about "just typing" vs. "typing and submitting". Just focus on typing and submitting, which is the majority of case. I suppose we could make this distinction, that writers are welcome to use "type" when it genuinely means that thing, but again, my interpretation is to simplify for the general writer audience. Either way, I actually wasn't involved in that guidance, just interpreting, so fine by me to add the great detail there. Thanks Steve.

**Comment by cbudz** [comment]
Guidelines LGTM 👍

**Pull request merged**
