### PR TITLE
[WIP] refactor to facilitate Vale rules extraction

### PR DESCRIPTION
**Pull request by aireilly**
Suggestion: Adding a `Correct form` entry for glossary terms would make creating Vale rules from the glossary more straightforward. Below is a sample refactor of the JBoss Community entry to illustrate this change. The proposal is to add a `Correct form` entry to every glossary entry.

### CODE REVIEW

**Comment by joaedwar** [comment]
Hi @aireilly. Thank you for submitting this PR. It is marked as a "WIP", but it seems you might want some feedback on the proposed idea? Maybe it is something we can discuss at the next meeting?

@bergerhoffer WDYT?

**Comment by bergerhoffer** [comment]
Thanks @joaedwar! We did have a discussion in the google chat room on this. I'm not a fan of adding another field, since the correct form of the term is already in the heading. I think we probably need to sync with the Vale group to learn more about how they're using the SSG, and to see if . @aireilly let me know if you want to set up a meeting to chat on this or anything!

 I'm going to mark this as "on hold" for now.

**Comment by aireilly** [comment]
Thanks @joaedwar @bergerhoffer - busy with OCP 4.10 stuff at the moment, would be great to catch up once that quiets down... :)

**Comment by Srivaralakshmi** [comment]
Hi @aireilly and @bergerhoffer :)

From the discussion, I gather that a meeting or chat on this issue is pending. Any updates on the progress of this PR?
Thanks!

**Comment by aireilly** [comment]
Hi @Srivaralakshmi @bergerhoffer No progress on this per se, but happy to take a few min to discuss Vale, what we have currently, and some future ideas. Should I put something in the calendar?

**Comment by mportman12** [comment]
@aireilly Can you make sure to include me on a meeting invite if you set one up?

**Comment by Srivaralakshmi** [comment]
Hi @bergerhoffer! Aidan wants to set up a meeting with you to discuss this. Is that ok with you?

**Comment by aireilly** [comment]
Discussed this PR with various interested parties. I'll propose a slightly different and less invasive solution presently. Closing this for now :)

**Pull request closed without merging**
