### PR TITLE
Adding what's new for February 2024

### PR DESCRIPTION
**Pull request by bergerhoffer**
Preview: https://file.rdu.redhat.com/~ahoffer/2024/main-feb-2024-history.html#february-2024

### CODE REVIEW

**Comment by bergerhoffer** [comment]
Wait til Feb is over in case anything else gets merged this month.

**Review by bburt-rh — DISMISSED** [review]
LGTM

**Review by bburt-rh — APPROVED** [review]
LGTM

**Review by mportman12 — APPROVED** [review]
LGTM

**Review by bburt-rh — APPROVED** [review]
lgtm

**Pull request merged**
