### PR TITLE
Adding customer to the glossary

### PR DESCRIPTION
**Pull request by bergerhoffer**
Addresses #198.

Preview: http://file.rdu.redhat.com/~ahoffer/style_guide/customer/master.html#customer

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@redhat-documentation/ccs-style-council For review please!

Description was adapted from what the IBM style council proposes adding to the ISG on this topic:

```
Red Hat always uses "customer", never "client", to refer to the people who buy, subscribe to, or use Red Hat products and services.
```

**Review by lahinson — APPROVED** [review]
LGTM

**Comment by dfitzmau** [comment]
LGTM

**Review by dfitzmau — APPROVED** [review]

**Review by ndeevy — APPROVED** [review]

**Review by joaedwar — APPROVED** [review]
LGTM

**Comment by bergerhoffer** [comment]
Thanks all! Merging since this has 3+ approvals

**Pull request merged**
