### PR TITLE
Adding and reorganizing style categories in the TOC

### PR DESCRIPTION
**Pull request by bergerhoffer**
I noticed that our "General formatting" TOC category has become pretty large and a "catch-all" for things that don't have a better home. I took a stab at creating a few new categories and moving things around.

Preview: http://file.rdu.redhat.com/~ahoffer/2022/master.html

New categories:

- "Grammar and language"
- "Formatting" (replaces "General formatting")
- "Structure"
- "Legal"
- "Release notes" (replaces "Specific documentation types")

I'm open to alternative category names, or whether certain guidelines belong in different sections - please weigh in!

Note that all actual guidance is straight copy/pasted and not changed in any way, so should not need to be reviewed word-by-word.

### CODE REVIEW

**Comment by bburt-rh** [comment]
@bergerhoffer - Thank you so much for doing this! I think this is a great idea and really clarifies the organization of the guide. It's a genuine improvement to the guide's usability. To me, the new categories make sense, and I can't think of others I'd add at this point. 

What do you think of the idea of alphabetizing all of the headings and subheadings underneath the `Style guidelines` section? Just a suggestion. The downside would be having to maintain alphabetical order going forward; we'd have to assume that anyone adding a new heading would know to insert it in it's correct alphabetical spot. WDYT? 

If not, then I have no other feedback and give it an lgtm.

**Review by ndeevy — APPROVED** [review]

**Comment by bergerhoffer** [comment]
@bburt-rh Great suggestion! I looked at the ISG and was surprised to see that the subsections were alphabetized in each category - I had never noticed that before.

I took a stab at alphabetizing all items under each category. I ended up renaming a few of the sections so that they showed up alphabetized with the most important wording. Can you please take a look?

Here are the heading changes I made, if people can please review:

Old | New
-- | --
References to 			Cost | Cost 			references
Statements 			about future releases or plans | Future 			releases or plans
Linking to 			Red Hat Knowledgebase articles | Red Hat 			Knowledgebase articles links
Lead-in 			sentences for Prerequisites and Procedure sections | Prerequisites 			and Procedure sections lead-in sentences
Commands with 			root privileges | Root 			privilege commands
Long code 			examples in procedures | Long code 			examples
Code example 			syntax highlighting | Syntax 			highlighting

@redhat-documentation/ccs-style-council Please review these heading updates to improve the alphabetizing of the style entries in each category. The preview is updated with the latest changes: http://file.rdu.redhat.com/~ahoffer/2022/master.html

No other changes have been made to the style entries in these PRs other than changing the order and the above titles.

**Comment by bergerhoffer** [comment]
Thanks @bburt-rh. You're right that some of them didn't sound quite right. I updated those 3.

Another change I made was to change the "Code examples" category to "Technical examples", in order to have a place for the new "IP address and MAC addresses" entry.

PTAL when you get a chance, thanks!

Preview is updated: http://file.rdu.redhat.com/~ahoffer/2022/master.html

**Comment by bergerhoffer** [comment]
Adding a new comment that has all the new/changed info in one spot (in addition to alphabetizing)

**New categories**

- "Grammar and language"
- "Formatting" (replaces "General formatting")
- "Technical examples" (replaces "Code examples")
- "Structure"
- "Legal"
- "Release notes" (replaces "Specific documentation types")

**Style entry heading changes**

Old  | New 
-- | --
References to 			Cost | Cost 			references
Statements 			about future releases or plans | Future 			releases or plans
Linking to 			Red Hat Knowledgebase articles | Links to Red Hat Knowledgebase articles
Lead-in 			sentences for Prerequisites and Procedure sections | Lead-in sentences
Commands with 			root privileges | Commands requiring root privileges
Long code 			examples in procedures | Long code 			examples
Code example 			syntax highlighting | Syntax 			highlighting

**Comment by bburt-rh** [comment]
Thanks, @bergerhoffer. This looks great. Lgtm and approved.

**Review by bburt-rh — APPROVED** [review]

**Review by joaedwar — APPROVED** [review]
lgtm

**Comment by ndeevy** [comment]
Great improvements, @bergerhoffer

**Review by ndeevy — APPROVED** [review]

**Pull request merged**
