### PR TITLE
GH#496: Added PR template

### PR DESCRIPTION
**Pull request by snarayan-redhat**
Issue: https://github.com/redhat-documentation/supplementary-style-guide/issues/496

Additional information:

### CODE REVIEW

**Review by bergerhoffer — APPROVED** [review]
In 26 June SSG meeting, agreed to merge this basic PR template first to test it out, then we can work to fill out additional details and instructions

**Comment by snarayan-redhat** [comment]
@redhat-documentation/ccs-style-council Can I get couple more approvals to merge?

**Review by ndeevy — APPROVED** [review]
Looks good to me.

**Review by dfitzmau — APPROVED** [review]

**Review by bredamc — APPROVED** [review]
LGTM

**Pull request merged**
