### PR TITLE
Noting that you have to be a member of the org to view the project m…

### PR DESCRIPTION
**Pull request by bergerhoffer**
…ember list

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@snarayan-redhat Can you review this?

**Review by snarayan-redhat — APPROVED** [review]

**Comment by snarayan-redhat** [comment]
@redhat-documentation/ccs-style-council This PR needs 2 more approvals

**Review by rolfedh — APPROVED** [review]
LGTM

**Review by dfitzmau — APPROVED** [review]

**Comment by dfitzmau** [comment]
LGTM

**Pull request merged**
