### PR TITLE
Updating to use the proper name of the IBM Style guide

### PR DESCRIPTION
**Pull request by bergerhoffer**
Per #264

Preview: http://file.rdu.redhat.com/~ahoffer/2022/main-ibm.html

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@bredamc if you wouldn't mind taking first review per our prior conversation!

**Review by ncbaratta — APPROVED** [review]
lgtm

**Review by IngridT1 — APPROVED** [review]
LGTM

**Review by bburt-rh — APPROVED** [review]

**Comment by bburt-rh** [comment]
lgtm

**Comment by bredamc** [comment]
@bergerhoffer Sorry to be so late reviewing this PR -- it all looks great. 

Just one very minor nitpick: we have two occurrences of "_IBM Style_ guide guidance", which reads a little awkwardly. Might we want to rewrite those two occurrences?

**Comment by bergerhoffer** [comment]
@bredamc It's too late for this PR since it has already merged, but if you'd like to submit a PR to make an update to those, that would be great!

**Comment by bredamc** [comment]
@bergerhoffer No worries, if you agree that we should make those changes, I'll submit a PR next week :)

**Comment by bredamc** [comment]
Additional changes in PR 268 https://github.com/redhat-documentation/supplementary-style-guide/pull/268

**Pull request merged**
