### PR TITLE
Adding disconnected term for OpenShift

### PR DESCRIPTION
**Pull request by bergerhoffer**
Addresses issue #187. 

Preview: http://file.rdu.redhat.com/~ahoffer/style_guide/disconnected/master.html#disconnected

### CODE REVIEW

**Comment by bergerhoffer** [comment]
Marking this WIP until I get sign off from OpenShift stakeholders on the wording.

**Comment by bredamc** [comment]
@bergerhoffer Are you still awaiting signoff from OpenShift stakeholders, or is this PR ready for review?

**Comment by bergerhoffer** [comment]
Sorry, I had the stakeholder discussion drag out and have been waiting for a reply for a few weeks. I've pinged them for final input this week, so this should be ready next week at the latest. Thanks!

**Comment by bergerhoffer** [comment]
The OCP PR for this has been merged, so this is now ready for review!

**Review by ncbaratta — APPROVED** [review]
lgtm

**Review by IngridT1 — APPROVED** [review]
LGTM

**Review by sbmetz — APPROVED** [review]
LGTM

**Review by bburt-rh — APPROVED** [review]

**Comment by bburt-rh** [comment]
lgtm

**Pull request merged**
