### PR TITLE
Add softirq to glossary

### PR DESCRIPTION
**Pull request by mmuehlfeldRH**
Add softirq to glossary

### CODE REVIEW

**Comment by mmuehlfeldRH** [comment]
I messed up my other [PR](https://github.com/redhat-documentation/supplementary-style-guide/pull/305) and, therefore, closed it. Sorry. This is the new one.

**Review by bergerhoffer — APPROVED** [review]
LGTM!

**Review by sbmetz — APPROVED** [review]
LGTM

**Review by bburt-rh — APPROVED** [review]

**Comment by bburt-rh** [comment]
lgtm. That makes 3 approvals, so I'm merging this.

**Pull request merged**
