### PR TITLE
Add section anchors

### PR DESCRIPTION
**Pull request by aireilly**
This change: 

* Removes `[discrete]` tags, thus allowing section anchors

Updated preview: https://file.emea.redhat.com/aireilly/ssg_links/

### CODE REVIEW

**Comment by aireilly** [comment]
There is a trade off here - the TOC levels are reduced. IMO it's an acceptable tradeoff. Section anchors are really useful for reviews.

**Comment by bergerhoffer** [comment]
@redhat-documentation/ccs-style-council This is a possible workaround to the limitation that we talked about at today's meeting when we talked about adding clickable headings.

In order to get the glossary terms to have clickable headings, but not show up in the TOC, they have to be bumped to a level 4. This PR adds some (unnecessary) extra headings (like "A-F") to bump them down. I'm not sure if these unnecessary headings are a worthwhile tradeoff, in order to have clickable glossary terms. (I can't decide for myself :smile:). 

PTAL at the preview and share your thoughts!

**Comment by mportman12** [comment]
Had a thought for the glossary:
---
1. Glossary of terms and conventions 
     1.1 Word usage 
          1.1.1 A 
          1.1.2 B 
          1.1.3 C 
          1.1.x Etc. 
     1.2 Symbols 
     1.3 Numbers 
---
This would allow us to achieve the desired ToC levels needed to create clickable glossary entries without everything showing up in the main ToC. There is redundancy, but it is minimal and isn't as intrusive as Aidan's initial suggestion of A-F etc.

**Comment by aireilly** [comment]
Sounds good @mportman12 ! Accidentally closed this PR. Let me know if you want me to reopen it. Thanks.

**Comment by bergerhoffer** [comment]
@mportman12 I like this option. It's still an unnecessary heading, but it's only 1 and it's not as intrusive. I think it's worth adding this to get the linkable glossary entries.

@aireilly I say go ahead and reopen this PR since you already did the work to remove the [discrete] tags. Then you'd just need to adjust the way @mportman12 proposed, if you're up for it. Or if you want to repush your commit (PR currently has 0), we could pull it down and continue it!

**Comment by aireilly** [comment]
NP, will reopen :)

**Comment by aireilly** [comment]
Closed accidentally.

**Comment by aireilly** [comment]
Updated

**Comment by aireilly** [comment]
Noting that for some reason we have duplicated the entries for 64-bit ARM (noun)?

**Comment by lahinson** [comment]
Hi @aireilly - Do you think this is ready to share with the group on #forum-ccs-style? We discussed this PR at today's CCS style guide meeting, and it sounded like we're all willing to move forward with the solution that Miriam proposed. If this is ready for reviews/approvals, I'm happy to post a reminder on the Slack channel, as I'm the style guide admin this week.

**Comment by aireilly** [comment]
This is ready to merge @lahinson :)

**Comment by mportman12** [comment]
@aireilly @bergerhoffer Could one of you build out a preview version of what this would look like in the UI? Would make it easier to review.

**Comment by bergerhoffer** [comment]
@aireilly would you mind providing a preview (and resolving the conflicts so that if it looks good, we can go ahead and approve)?

The script doesn't work for me right now, something with podman, and I haven't had time to look into it yet.

**Comment by aireilly** [comment]
Sure thing - when I return from PTO.

**Comment by aireilly** [comment]
We should investigate PR preview builds too I think.

**Comment by aireilly** [comment]
@bergerhoffer @mportman12 Updated the preview, PTAL: https://file.emea.redhat.com/aireilly/ssg_links/

**Review by mportman12 — APPROVED** [review]
LGTM!

**Review by joaedwar — APPROVED** [review]
lgtm

**Review by bergerhoffer — APPROVED** [review]
This LGTM!

**Pull request merged**
