### PR TITLE
Ellipses yaml code blocks

### PR DESCRIPTION
**Pull request by apinnick**
Issue: None

Additional information: Review comments in https://github.com/redhat-documentation/supplementary-style-guide/pull/517

### CODE REVIEW

**Review by dfitzmau — APPROVED** [review]

**Review by ndeevy — APPROVED** [review]
LGTM

**Comment by bredamc** [comment]
@apinnick Just to explain my request to show both the code and the rendered output for the example -- it's not clear to me whether the workaround of prefixing the ellipsis with ` #`  will render the ellipsis correctly in the output, or comment it out so that it is no longer visible?

**Comment by apinnick** [comment]
> @apinnick Just to explain my request to show both the code and the rendered output for the example -- it's not clear to me whether the workaround of prefixing the ellipsis with ` #` will render the ellipsis correctly in the output, or comment it out so that it is no longer visible?

This is not a workaround. It's standard YAML. 

The `#` will always render because it is inside a code block.

**Review by bredamc — APPROVED** [review]
LGTM

**Pull request merged**
