### PR TITLE
Updates to avoid 'guide guidance'

### PR DESCRIPTION
**Pull request by bredamc**
Addendum to PR 265:
https://github.com/redhat-documentation/supplementary-style-guide/pull/265

### CODE REVIEW

**Comment by bredamc** [comment]
@bergerhoffer Ready for you to review :)

**Review by sbmetz — APPROVED** [review]
LGTM!

**Review by mportman12 — APPROVED** [review]
LGTM

**Review by mportman12 — APPROVED** [review]
LGTM

**Review by Amrita42 — APPROVED** [review]

**Comment by Amrita42** [comment]
lgtm

**Pull request merged**
