### PR TITLE
issue-491-update-tech-preview-template-wording

### PR DESCRIPTION
**Pull request by bburt-rh**
This PR updates the tech preview template to address #491

### CODE REVIEW

**Review by lahinson — APPROVED** [review]
The text looks good to me. My one suggestion would be to consider moving it out of the note and into the bulleted list of guidelines.

**Comment by bburt-rh** [comment]
Thanks @lahinson. I agree that it should be taken out of a Note admonition, but instead of moving it to the bulleted list, I added it to the lead-in sentence. LMK what you think. Thanks!

**Review by bergerhoffer — APPROVED** [review]
LGTM!

**Review by lahinson — APPROVED** [review]
LGTM!

**Review by sbmetz — APPROVED** [review]
LGTM!

**Pull request merged**
